[scripts]
build = "cargo build"
test = "cargo test"
dev = "cargo watch -x \"run\"" # Run `cargo install cargo-watch` to add Cargo Watch for this

# Releases the project (maintainers only)
# We commit all staged files so we can manually bump the Cargo version
release = "standard-version --sign --commit-all && git push --follow-tags origin main"
