[package]
name = "bonnie"
version = "0.1.0"
authors = ["arctic_hen7 <arctic_hen7@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.8"
serde = { version = "1.0.125", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
url = "2.2.2"
flate2 = "1.0.20"
tar = "0.4.33"
dircpy="0.3.6"

[lib]
name = "bonnie_lib"

[[bin]]
name = "bonnie"
path = "src/bin/main.rs"