# Builds releases for the three major OSes
name: build-releases

# This will run whenever a new tag is released
on:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: bonnie
            asset_name: bonnie-linux-amd64
          - os: macos-latest
            artifact_name: bonnie
            asset_name: mything-macos-amd64
          - os: windows-latest
            artifact_name: bonnie.exe
            asset_name: bonnie-windows-amd64
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: cargo check && cargo fmt -- --check && cargo clippy && cargo test
      - name: Build
        run: cargo build --release --locked
      - name: Release
        uses: marvinpinto/action-automatic-releases@v1.1.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          files: |
            LICENSE.txt
            README.md
            target/release/${{ matrix.artifact_name }}
