name: Build and Release

on:
    push:
        tags:
            - "v*"

jobs:
    # This builds and releases for Windows, MacOS, and Linux
    usu-build-release:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      artifact_name: bonnie
                      asset_name: bonnie-linux-amd64
                    - os: macos-latest
                      artifact_name: bonnie
                      asset_name: bonnie-macos-amd64
                    - os: windows-latest
                      artifact_name: bonnie.exe
                      asset_name: bonnie-windows-amd64
        steps:
            - uses: actions/checkout@v2
            - name: Read CHANGELOG
              id: read_release
              shell: bash
              run: |
                  r=$(cat CHANGELOG.md)
                  r="${r//'%'/'%25'}"                               # Multiline escape sequences for %
                  r="${r//$'\n'/'%0A'}"                             # Multiline escape sequences for '\n'
                  r="${r//$'\r'/'%0D'}"                             # Multiline escape sequences for '\r'
                  echo "::set-output name=RELEASE_BODY::$r"         # Set environment variable
            - name: Build
              run: cargo build --release --locked
            - name: Release binary
              uses: svenstaro/upload-release-action@v1-release
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: target/release/${{ matrix.artifact_name }}
                  asset_name: ${{ matrix.asset_name }}
                  tag: ${{ github.ref }}
                  body: ${{ steps.read_release.outputs.RELEASE_BODY }}
    # This builds and releases for musl
    musl-build-release:
        runs-on: ubuntu-latest # We cross-compile from Ubuntu
        steps:
            - uses: actions/checkout@v2
            - name: Read CHANGELOG
              id: read_release
              shell: bash
              run: |
                  r=$(cat CHANGELOG.md)
                  r="${r//'%'/'%25'}"                               # Multiline escape sequences for %
                  r="${r//$'\n'/'%0A'}"                             # Multiline escape sequences for '\n'
                  r="${r//$'\r'/'%0D'}"                             # Multiline escape sequences for '\r'
                  echo "::set-output name=RELEASE_BODY::$r"         # Set environment variable
            - name: Install musl toolchain
              run: rustup target add x86_64-unknown-linux-musl
            - name: Build
              run: cargo build --release --target x86_64-unknown-linux-musl --locked
            - name: Release binary
              uses: svenstaro/upload-release-action@v1-release
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: target/x86_64-unknown-linux-musl/release/bonnie
                  asset_name: bonnie-musl-amd64
                  tag: ${{ github.ref }}
                  body: ${{ steps.read_release.outputs.RELEASE_BODY }}
